### ISSUE TITLE
About the accuracy of 93.4 mentioned in the paper.

### ISSUE THREAD

**Issue by CodeLHY** [voidrank/Geo-CNN#6]
hi @voidrank ,
First of all, it is really excellent work!
Have you even got the accuracy that mentioned this the paper?  What is the best score have you ever got?

**Comment by voidrank** [comment]
@CodeLHY Yes, the performance of our model on ModelNet40 ranges from 93.2 to 9.38.

**Comment by CodeLHY** [comment]
> @CodeLHY Yes, the performance of our model on ModelNet40 ranges from 93.2 to 9.38.

Thank you for your reply!
